---
title: "Teaching Philosophy"
output: html_document
---


I see teaching as a way to encourage students to think differently about something they thought they understood, while enriching that understanding with new content. When I first approach a course, I consider the learning objectives to ensure that they focus on two types of skills – a substantive skill (mastery of content) and a technical skill (mastery of a type of assessment, e.g. writing short papers). I design learning objectives that are measureable and then I work backwards to ensure that how I design my course supports these goals. Over the quarter, students will have repeated opportunities to develop a skill with low-stakes assessments while they get clear feedback on why and how this skill matters for the learning objective and in a broader scheme of their education or the discipline.

I work to maintain transparency in why we are doing what we are doing – reading a chapter, practicing a method, writing a paper—by showing how it builds to the whole and contributes to our learning objectives. I’ve recently begun using a ‘course map’ as it can help formalize the connection between the content and learning objectives to ensure that the assignments build and support objectives. In this way, I have a course with a clear and strong foundation to prepare and help students reach defined goals. 

In the classroom, I incorporate elements of fun and excitement about the topic that can be contagious for the students. I also employ an approach that is somewhat ‘flipped’ in the sense that we emphasize important concepts through application and build on the readings. When we talk about, for example, why institutions matter, we might consider something like the recent tax bill and discuss the types of behaviors it incentivizes or disincentives. Then, we explore this in the course context – what are the ‘rules’ of the bill and how might people react? I work to ensure that there are tangible connections between our course content and reality. This resonates with students and it often helps make what we’re doing ‘real’ in a sense they hadn’t considered before.

I use the same approach in my ‘methods’ courses – although we are learning more technical skills, we can still use and apply these skills in a substantive context. The two aspects I work to highlight are that there is often no ‘universal’ right choice—many students think of statistics as having one set answer when in reality there are many possible routes or applications one might select—and that there is a broader real-world context for what we are learning and there are implications to getting it ‘wrong.’  

Finally, I see my role as one of a mentor: showing students why, how and what concepts really matter. I do the same for my teaching assistants as we work together to support the course goals, such as holding joint sessions where we collectively discuss grading and different assessments. I also allow them to be as active in the mentoring process as they would like because an instructor, faculty or graduate student, who is interested in and excited by the material is typically going to be better able to reach students and deliver the content than one who is passive or uninterested. In sum, I work hard and demand a lot from my students and myself, endeavoring to ensure that I balance the workload so that assignments make sense, support goals and help students work toward mastery of the content and a particular skill. 
